### ISSUE TITLE
Loading spin on form page

### ISSUE THREAD

**Issue by mcristaldo** [jfoclpf/autocosts#102]
It would be nice to have a loading spinner GIF while the page is loading. It takes 4-5 secs to load the entire page. This way they will know that the content is loading, otherwise it can cause uncertainty on the user.

GIF: 
![form-page-loading](https://user-images.githubusercontent.com/11855774/51200224-a7936200-18d7-11e9-8551-e70c9f728d3c.gif)

Thoughts?

**Comment by mcristaldo** [comment]
I'm sharing a loader in two formats, GIF and SVG
SVG: https://www.dropbox.com/s/ww0uzfn4rsteel8/loader.svg?dl=0
GIF: https://www.dropbox.com/s/41zjim3koaxjmp4/loader.gif?dl=0

**Comment by jfoclpf** [comment]
> Looks great

I will use them

**Comment by jfoclpf** [comment]
@mcristaldo I think I solved this issue with ef1a94c17cfaa078382ccfd80b626023d829096c, if not kindly reopen it

**Comment by mcristaldo** [comment]
Hi @jfoclpf 
I just checked it out on Chrome incognito mode, it doesn't show up. Where did you test it?

**Comment by jfoclpf** [comment]
Hi Martin
I tested on autocosts.work
I tested now on my phone and it shows the spinning loader
It's not yet in production

**Comment by mcristaldo** [comment]
Oh I tested on .info site, sorry.
It works on Chrome in my Mac, but I'm not able to see it in my iPhone because that home page issue.

**Comment by jfoclpf** [comment]
Ok, we can close this issue then.

I will try to solve this iOS/iPhone issue #106 today, but I still didn't
find an easy way to test it on my Ubuntu.
