### ISSUE TITLE
Social media icons are missing 

### ISSUE THREAD

**Issue by mcristaldo** [jfoclpf/autocosts#103]
In the results page, the social media icons are missing. Is it on purpose, it has a display: none property applied to it
SS: 
https://www.dropbox.com/s/dfvavvjtqzbjcqu/Captura%20de%20pantalla%202019-01-15%2015.19.43.png?dl=0

**Comment by jfoclpf** [comment]
solved
please check https://autocustos.info and if error persist please reopen issue

**Comment by mcristaldo** [comment]
It does works now. The links works perfectly too. Cool!


Martín Cristaldo UI/UX designer
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
www.mct.uy
Dribbble: m_cristaldo <https://dribbble.com/m_cristaldo>
Twitter: @m_cristaldo <https://twitter.com/m_cristaldo>
Instagram: mctuy <https://instagram.com/mctuy/>
Blog: @mcristaldo <https://medium.com/@mcristaldo>
