### ISSUE TITLE
Results page: "Total" doesn't fit well

### ISSUE THREAD

**Issue by mcristaldo** [jfoclpf/autocosts#104]
![captura de pantalla 2019-01-15 15 22 00](https://user-images.githubusercontent.com/11855774/51200869-63a15c80-18d9-11e9-82fd-c3dff32e0213.png)

I think we can use only "Total" at the bottom of these section. We already have the title at the top, I don't think we need to repeat it at the bottom. I'm not sure if it's possible at this stage though.

Thoughts?

**Comment by jfoclpf** [comment]
Perfectly agreed. I will do it

>

**Comment by jfoclpf** [comment]
solved with eecd4f7fa7c9cf99fc24766d54189e79d1514690
