### ISSUE TITLE
Results page: "Print" doesn't work

### ISSUE THREAD

**Issue by mcristaldo** [jfoclpf/autocosts#105]
When I hit on "Print" button nothing happens

**Comment by jfoclpf** [comment]
solved by 8f0930fa9a0b97e91a7bbc9f9c7870b3fbfb1d31...a2e23205c0d582b13bebec5d09ece32a0f0ebb27

@mcristaldo please test it, 
if the issue is still there, kindly reopen the issue

**Comment by mcristaldo** [comment]
@jfoclpf 
Yeah it works well. It would be nice if it opens up in a new tab though.

**Comment by jfoclpf** [comment]
Thanks Martin for the feedback
It cannot open on the new tab, because the browser (sometimes Adblock)
blocks it.
It was previously like that, and that was the reason for not working
