### ISSUE TITLE
Logo for facebook

### ISSUE THREAD

**Issue by jfoclpf** [jfoclpf/autocosts#115]
Create a logo for Facebook: 
 - size in pixels is 1200 x 630px
 - Aspect ratio should be 1.91:1
 - png or gif or jpg format (apparently facebook doesn't like svg) 

from [SO](https://stackoverflow.com/questions/18835027/new-ogimage-size-for-facebook-share).

@mcristaldo can you make a logo (the same car, the same colours, the same theme) that satisfies these rules? Do you think is achievable?

I should myself upload and then check and confirm on [Facebook sharer debugger](https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fautocustos.info%2FPT)

**Comment by jfoclpf** [comment]
More on facebook images, from facebook blog:
[Facebook Docs - Image Optimization for Link Page Posts.pdf](https://github.com/jfoclpf/autocosts/files/2861997/Facebook.Docs.-.Image.Optimization.for.Link.Page.Posts.pdf)

**Comment by jfoclpf** [comment]
Facebook uses Open Graph
http://ogp.me/

Therefore the image property should be, for example

```html
<meta property="og:image" content="{{{clientData.basicURL}}}/logo1200x630.png" />
<meta property="og:image:type" content="image/jpeg" />
<meta property="og:image:width" content="1200" />
<meta property="og:image:height" content="630" />
<meta property="og:image:alt" content="An icon representing a colorful symetric car, having a dollar sign inside it" />
```

We can have several images, with different sizes (og array)

```html
<meta property="og:image" content="{{{clientData.basicURL}}}/logo1200x630.png" />
<meta property="og:image:type" content="image/jpeg" />
<meta property="og:image:width" content="1200" />
<meta property="og:image:height" content="630" />
<meta property="og:image:alt" content="An icon representing a colorful symetric car, having a dollar sign inside it" />
<meta property="og:image" content="{{{clientData.basicURL}}}/logo600x315.png" />
<meta property="og:image:type" content="image/jpeg" />
<meta property="og:image:width" content="600" />
<meta property="og:image:height" content="315" />
<meta property="og:image:alt" content="An icon representing a colorful symetric car, having a dollar sign inside it" />
```

**Comment by mcristaldo** [comment]
Hey Joao, 
Sorry for the delay, I took the last week off. 
I will work on the image for facebook during this week. 

Thank you.

**Comment by jfoclpf** [comment]
Hi @mcristaldo , no worries, I'm already making the logos.
Thanks anyway
cheers

**Comment by jfoclpf** [comment]
solved with 32262388e14a01b4ed5cf29e21d188d2d67bc48d and 30479517d8b59f3c3e93a871ccc70be475f3fc17

**Comment by mcristaldo** [comment]
Oh ok, sorry for the late notice though. Thank you!
Martín Cristaldo UI/UX designer
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -
www.mct.uy
Dribbble: m_cristaldo <https://dribbble.com/m_cristaldo>
Twitter: @m_cristaldo <https://twitter.com/m_cristaldo>
Instagram: mctuy <https://instagram.com/mctuy/>
Blog: @mcristaldo <https://medium.com/@mcristaldo>

**Comment by jfoclpf** [comment]
No problem :)
