### ISSUE TITLE
Disappearing the right-top button on main page

### ISSUE THREAD

**Issue by MobiTech1191** [jfoclpf/autocosts#118]
When I load [the website](https://autocosts.info/US) for the first time, I can see `the right-top button` on page.

But after I refresh [the website](https://autocosts.info/US),`the right-top button` disappears. 
I tried to double check this issue on Chrome, Firefox, and Safari. 
The same issue happened on all browsers.

![true](https://user-images.githubusercontent.com/38475771/52992210-9a7cfd80-33c4-11e9-9030-5cc9977afede.png)
![error](https://user-images.githubusercontent.com/38475771/52992214-9f41b180-33c4-11e9-9ef0-04becf2bd0a6.png)

**Comment by jfoclpf** [comment]
I think it's already working. Can you confirm?

**Comment by MobiTech1191** [comment]
Ok, let me check it again. Thanks
