### ISSUE TITLE
Move sentence from text to button

### ISSUE THREAD

**Issue by jfoclpf** [jfoclpf/autocosts#121]
On the landing page and according to @mcristaldo suggestions, I shall move the text "Find the True Cost of your Car" to the button which has the text "Calcuate car costs". That is, the text "Calcuate car costs" should be replaced by "Find the True Cost of your Car", on the landing page.

**Comment by jfoclpf** [comment]
@mcristaldo what do you think now?
https://autocostos.info/US

**Comment by mcristaldo** [comment]
Hey Joao, 
Looks good. Please keep me updated about how it works. I want to know if this tiny update change anything on the user behavior. 
Btw, why I'm not able to see all the steps at once now?
https://www.dropbox.com/s/q8y2gifkbomqml8/Captura%20de%20pantalla%202019-03-19%2011.28.16.png?dl=0

**Comment by jfoclpf** [comment]
Thanks. Yes I will keep you updated.

Regarding the steps, I realized that the number of people who finished the
form was decreasing sharply (the statistics take time to be fully updated
after the new design). I thought the users were being "scared" knowing they
had to fill so many steps.

What do you think Martin?

**Comment by mcristaldo** [comment]
I see your point. But I don't see any advantage in hiding it though. I creates uncertainty on the user cause they don't know how many steps they will need to take. It can be perceptive as if you're cheating them, which is not something good.
If you agree I can work on a couple of possible solutions, I have some ideas that can help to improve the user experience and hopefully convert more. Just let me know.

**Comment by jfoclpf** [comment]
Thanks for the feedback Martin, and yes, go ahead. Think of some user
experience solution to improve this issue!
