### ISSUE TITLE
Too many font sources

### ISSUE THREAD

**Issue by jfoclpf** [jfoclpf/autocosts#122]
Hi @mcristaldo 
How do you do? Hope fine!

Do we need all these fonts?
https://github.com/jfoclpf/autocosts/blob/master/src/css/fonts.css

It's time to load, specially on the landing page.

Which fonts do we really need? 

Furthermore I'm having a lot of css validating warnings on this file
`message: 'Redefinition of “font-family”',`

Thanks

**Comment by jfoclpf** [comment]
Oh, now I see, you use different `unicode-range` segements

> The purpose of this descriptor is to allow the font resources to be segmented so that a browser only needs to download the font resource needed for the text content of a particular page.

in https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/unicode-range

And indeed it works, since the browser only downloads what is needed, as seen by Google Dev Console (downloads only 3 files and `fonts.css` declares 6 files)

![image](https://user-images.githubusercontent.com/3984909/54128125-ad0ab580-440b-11e9-9737-25cab1eade23.png)

I'm just struggling with a W3 css validating warning: `   message: 'Redefinition of “font-family”',` but maybe we just ignore it, furthermore it's a warning not an error

**Comment by mcristaldo** [comment]
Hi Joao, 

Actually I don't recall creating that font.css file. It's a Google font, so I only added this line to get the font working
<link href="https://fonts.googleapis.com/css?family=Nunito:400,700" rel="stylesheet">

But yeah as you mentioned it seems to use different unicode-range base on language

**Comment by jfoclpf** [comment]
Hi @mcristaldo 
Thanks

Yes, it is indeed just a warning and a pending issue within W3C
https://lists.w3.org/Archives/Public/www-style/2014Nov/0266.html

Cheers
