### ISSUE TITLE
Add further icons for table JPG image and for world stats on the right corner

### ISSUE THREAD

**Issue by jfoclpf** [jfoclpf/autocosts#137]
![image](https://user-images.githubusercontent.com/3984909/79390450-febb3300-7f6f-11ea-845e-55190252e403.png)

Use icons of https://www.flaticon.com/ as @mcristaldo had already used such database for other icons

I should thus add 2 extra icons on the left side of the "download" icon

 - the download button should download directly the JPG image table
 - the table icon should forward to the tables section at `/tables/XX.htm`
 - the world icon should direct to the world stats at `/stats`

**Comment by jfoclpf** [comment]
@mcristaldo can you just generate a "world icon" and a "table-like icon"?

**Comment by mcristaldo** [comment]
@jfoclpf Hi Joao,
I'm attaching the proposed solution. 
I think it's important to label the icons here to make it clear what the actions would be once users click on it.
Please let me know your thoughts
![ac_average_modal-v2](https://user-images.githubusercontent.com/11855774/79773947-7db1c200-8308-11ea-8524-9667cffc7550.png)

**Comment by jfoclpf** [comment]
Great Martin, thanks a lot

But I need two extra icons, for the tables as such

 - World stats: https://autocosts.info/stats (the world icon there is
great, thanks)
 - The Table as JPG Image: https://autocosts.info/tables/BO.jpg (missing
icon)
 - The Table as HTML: https://autocosts.info/tables/BO.htm (missing icon)

Remove the icon for download, cause I don't this it's fully appropriate

You're right, I also agree the labels are important and should be there

João Pimentel Ferreira <https://www.joaopimentel.com>

**Comment by mcristaldo** [comment]
Hi Joao, 

Here are the icons: https://www.dropbox.com/sh/ttlzkpmwd61hw7g/AAAjxT67YZHXtY8WwTzvxUtga?dl=0
In that folder you can find: globe, html and table icons in SVG format (same format used in the website)
If you need them in a different format please let me know

**Comment by jfoclpf** [comment]
Great, thanks

>

**Comment by jfoclpf** [comment]
I just add here the files for registering purposes


[logos.zip](https://github.com/jfoclpf/autocosts/files/4545538/logos.zip)

**Comment by jfoclpf** [comment]
done it, thanks @mcristaldo
