### ISSUE TITLE
 Step 1  |  Car acquisition date 

### ISSUE THREAD

**Issue by jfoclpf** [jfoclpf/autocosts#33]
Old input: 
![image](https://user-images.githubusercontent.com/3984909/40586183-cec0945e-61be-11e8-87f0-4e49505bef70.png)

New input:
![image](https://user-images.githubusercontent.com/3984909/40586184-d35063b4-61be-11e8-801f-8acce4856901.png)

Since in the new design we do have a field to enter a completed date (DD/MM/AAAA) I changed the input type to "date" instead of having 2 fields for Month and Year. So because of that I also changed the id and name to make these more accurate.

**Comment by mcristaldo** [comment]
Oh ok gotcha, I will update it so we have month and year only. Thanks

**Comment by jfoclpf** [comment]
Thank you. 
when you do it, don't forget to commit the code here, otherwise it will be lost from the server, when I update the code
Thank you

**Comment by jfoclpf** [comment]
Done it with f69d7b5e0dfd664be19674c8c99dcb2f1ef34ffa
