### ISSUE TITLE
Text issues

### ISSUE THREAD

**Issue by jfoclpf** [jfoclpf/autocosts#37]
There are some phrases starting with lowercase. like this one "if new, the price you paid...."
![image](https://user-images.githubusercontent.com/3984909/40586242-147f1186-61c0-11e8-8217-187d44a78e3d.png)

I'm not able to fix it using CSS only, would you tell me where can I fix those?

**Comment by jfoclpf** [comment]
I can fix those.
Can you tell me exactly which phrases shall start with capital?

**Comment by mcristaldo** [comment]
I'm listing the phrases below:

1.
**Now**
if new, the price you paid for the car
if used, the commercial value the car had when you acquired it
**Should read**
If new, the price you paid for the car
If used, the commercial value the car had when you acquired it

2.
**Now**
if you sell it now, how much would you get?
**Should read:**
If you sell it now, how much would you get?

3.
**Now**
Average amount spent with tolls
bridges, tunnels, motorways and congestion charges to gain access to city-centre
**Should read** (: is missing)
Average amount spent with tolls:
bridges, tunnels, motorways and congestion charges to gain access to city-centre

4.
**Now**
if public transport isn't an option for you, insert 0
**Should read**
If public transport isn't an option for you, insert 0

**Comment by jfoclpf** [comment]
Done it with commit [cb20d96](https://github.com/jfoclpf/autocosts/commit/af7c251932eb0e5fba3185ab9ea196c6ec304e03)
