### ISSUE TITLE
Transitions in the form amongst sections

### ISSUE THREAD

**Issue by jfoclpf** [jfoclpf/autocosts#40]
1. The "Next" button shouldn't be seen until the user complete the field/s needed
Not completed field
https://www.dropbox.com/s/yi8dwh6dakp48dn/Captura%20de%20pantalla%202018-06-12%2015.08.59.png?dl=0
Field completed ("Next" button appears)
https://www.dropbox.com/s/4ozpkybm5a0ugzc/Captura%20de%20pantalla%202018-06-12%2015.08.43.png?dl=0-- 

2. Once the field/s are completed, the user would be able to go to the next question by clicking on "Next" or pressing Enter/Tab
https://www.dropbox.com/s/l7ja2c1r09pjgap/Captura%20de%20pantalla%202018-06-12%2015.10.04.png?dl=0

3. Once the user click on "Next" or pres Enter/Tab and go to next question, the question should scroll up and and fade, so the next question should come from the bottom to be the main focus on the screen.
https://www.dropbox.com/s/8gf6077ym62rkkk/Captura%20de%20pantalla%202018-06-12%2015.10.47.png?dl=0

4. The steps need to be synchronized with the form. These are the 3 possible states:
Active: https://www.dropbox.com/s/8nvr1vygsqg5887/Captura%20de%20pantalla%202018-06-12%2015.13.31.png?dl=0
Completed: https://www.dropbox.com/s/poouj15ypuz7l6x/Captura%20de%20pantalla%202018-06-12%2015.15.14.png?dl=0
Next steps: https://www.dropbox.com/s/8sfwmxbfvf3ztmt/Captura%20de%20pantalla%202018-06-12%2015.15.45.png?dl=0

5. Once the user complete step 1 and 2, the "Calculate Cost" button should appear.
https://www.dropbox.com/s/ay0o8utl1y8jmvv/Captura%20de%20pantalla%202018-06-12%2015.22.30.png?dl=0

6. When the site loads the first thing seen are the modals opened, it loads first. The home page should loads first

7. When a modal opens it has a weird effect that doesn't look good. It should work as this.
https://www.dropbox.com/s/ot2cbz3m4wdpo2e/modal_animation.gif?dl=0

**Comment by jfoclpf** [comment]
@mcristaldo 

should the fields not yet filled be visible? I mean, the fields at the end of the form should be visible right from the beginning? Or do you mean, that the next field is only visible when user presses Next?

**Comment by jfoclpf** [comment]
@mcristaldo 
What do you have in mind, when for example, the user in the month field, which can be only an integer of 1 to 12, puts 1.5?

- The next button doesn't appear
- The next button appear and as it is pressed an alert appears with an error?

What do you think it's better?

**Comment by jfoclpf** [comment]
according to @mcristaldo it shoud work like this
- The only visible field/s are the one related to the step (it could be one or more fields though), it means the one/s the user is completing 
- The user needs to complete the field before and click on Next to see the next question
- The user can go back to the previous question already answered by scrolling up

**Comment by jfoclpf** [comment]
My question is, what do you mean by "complete de field"?

It is "complete correctly" or just insert some data? 

It should be nice to avoid alerts. What about a faded out button, before it's correctly filled?

**Comment by mcristaldo** [comment]
I think we can prevent it by letting the user only enter the info we want. So for example for the month  they should be able to enter a number from 1 to 12 only in their keyboard/phone.
If they type 1 and then they try to type a #4 to enter 14, it just won't work, is there a way to do that?
Although it would be nice to list all the months by name :/

**Comment by jfoclpf** [comment]
Yes, i like that idea. We should avoid using alerts. Yes, it is possible to
avoid the insertion of data that we don't want.

We can't use the months names because it would need a huge amount of new
strings for the several languages :)
