### ISSUE TITLE
User input verification on particular number field

### ISSUE THREAD

**Issue by jfoclpf** [jfoclpf/autocosts#43]
@mcristaldo said

> Also, I think we can prevent some errors by letting the user enter only what's needed. For example in the first question Car acquisition date I'm able to enter whatever I want, but then after completing the next 2 questions the button Next doesn't appear. I think we should let the user know what the error is OR even better imo just let them put valid year.

![autocosts_fields](https://user-images.githubusercontent.com/3984909/42710181-42979e38-86e3-11e8-8deb-eb754d11c6e7.gif)

**Comment by jfoclpf** [comment]
@mcristaldo 
what do you think about this class "wrong", and add to the input when the input is wrong

```
input.wrong{
  border: solid 1px red;
  border-radius: 5px;
}
```

**Comment by jfoclpf** [comment]
@mcristaldo 

what do you think about this

![image](https://user-images.githubusercontent.com/3984909/42724735-280188fa-8778-11e8-8d5c-430f00829970.png)

**Comment by mcristaldo** [comment]
Hi Joao, 
It seems it got lost but actually I sent this to you by email
![error_message](https://user-images.githubusercontent.com/11855774/42900839-5054f492-8aa0-11e8-979e-3bc0136b0963.png)
Did you add that "wrong" class in the style.css file? I can adjust to fit the design I did if you want

**Comment by mcristaldo** [comment]
Don't you think that it can be only in english at least?

In the steps I would do the the text red too, not only the dot. I can adjust it though

**Comment by jfoclpf** [comment]
Yes, it would be possible to add text in all languages, but we have to arrange something considering the available strings

```
    "error_invalid_insu_value" : "Invalid insurance amount",
    "error_insu_period" : "Insert payment frequency of insurance payments",
    "error_fuel_curr_dist" : "You must determine if you want to make calculations based on kilometres or AUD",
    "error_fuel_car_eff" : "Invalid gas efficiency amount",
    "error_fuel_price" : "Invalid gas price",
    "error_car_job" : "Please indicate if you take your car to the workplace",
    "error_fuel_dist" : "Invalid amount of kilometres traveled per month",
    "error_days_per_week" : "Invalid number of days per week",
    "error_dist_home_work" : "Invalid kilometres between home and the workplace",
    "error_dist_no_job" : "Invalid number of kilometres you drive during the days you don't drive your car to the workplace",
    "error_currency" : "Invalid USD per month",
    "error_depreciation_month" : "Invalid acquisition month",
    "error_depreciation_year" : "Invalid acquisition year",
    "error_depreciation_value" : "Invalid acquisition amount",
    "error_depreciation_value_today" : "Invalid present vehicle value",
    "error_depreciation_date" : "Invalid acquisition date",
    "error_depreciation_new_car" : "The depreciation does not apply because this vehicle is new",
    "error_credit_question" : "Please determine if you used car financing",
    "error_credit_loan_value" : "Invalid financed amount",
    "error_credit_period" : "Invalid period of credit, number of installment payments",
    "error_credit_instalment" : "Invalid installment amount",
    "error_credit_residual_value" : "Invalid residual value",
    "error_inspection_ntimes" : "Invalid number of times",
    "error_inspection_costs" : "Invalid inspection cost",
    "invalid_amount" : "Invalid amount",
    "invalid_nbr_pp" : "Invalid number of people",
    "error_pass_amount" : "Invalid monthly ticket amount",
    "error_income" : "Invalid net income",
    "error_weeks_per_year" : "Invalid number of weeks per year",
    "error_months_per_year" : "Invalid number of months per year",
    "error_hours_per_week" : "Invalid number of hours per week",
    "error_min_drive_home_job" : "Invalid number of minutes you drive from home to workplace",
    "error_min_drive_weekend" : "Invalid number of minutes you drive in the days you don't take the car to workplace",
    "error_min_drive" : "Invalid number of minutes you drive",
    "error_days_per_month" : "Invalid number of days per month",
```

>  I can adjust it though if you want

yes, please. But please, commit also here in github, and review your changes to be sure that you just amend what you expect

**Comment by mcristaldo** [comment]
Hi Joao, I think the "wrong" class is not taking place in the right place, the class appears in the next field and not in the the that actually has an error. 
Please check the image attached
![captura de pantalla 2018-07-18 22 24 17](https://user-images.githubusercontent.com/11855774/42915852-a6d7ef4e-8ad8-11e8-8c84-580ebb3b8600.png)

The error should be on "Depreciation of the vehicle" and not on "Vehicle insurance and breakdown coverage"

Also would you please change the border color and thickness of the error field to:
border-bottom: 2px solid #ef474c

Thank you.

**Comment by jfoclpf** [comment]
Ah, I see what you mean. No, it's correct, but it's not fully clear

1. You are editing the "Depreciation", therefore you see round blue, which means "you're there" whether it's correct or wrong

2. Vehicle insurance is "red" because you went there, and you didn't fill anything, therefore is empty and thus is wrong.

Maybe it should be more clear.

**Comment by mcristaldo** [comment]
Oh I see, yeah it's confusing. 
I think the step should be red even if you're editing the question, otherwise the user might think the issue was solved

**Comment by jfoclpf** [comment]
Hi Martin
I used your css. Thanks

1. I solved the issue of the confusing icons as you suggested

2. I added error message under the number input as you suggested. I had to stick with English. I will see later.

Can you check now and say what you think?
https://autocosts.work/US

**Comment by mcristaldo** [comment]
Now I can see the red dot everytime I got to the next question. The red dot (worng class) has to appear only if:
1. The user entered invalid info/value
2. The user didn't complete the question and goes to the next one somehow
Otherwise we should't show it imo.

See attached GIF please
![error_issue](https://user-images.githubusercontent.com/11855774/42967678-692b49f8-8b77-11e8-9f78-276a15e7e001.gif)

**Comment by jfoclpf** [comment]
Hi @mcristaldo I was improving here several functions
can you test now and tell me what do you think?
https://autocosts.work/

**Comment by jfoclpf** [comment]
is it solved Martin?


João Pimentel Ferreira <http://joaopimentel.eu>

**Comment by jfoclpf** [comment]
@mcristaldo is this issue solved?

**Comment by mcristaldo** [comment]
Solved
