### ISSUE TITLE
#2 and #3 circles active mode

### ISSUE THREAD

**Issue by mcristaldo** [jfoclpf/autocosts#45]
Once the user reaches to step 2 or 3 the big circle with the number should in active mode as the #1 circle
The class is already created, the big circles (#2, #3) need the "active" class once the user get there only

**Comment by jfoclpf** [comment]
Hi @mcristaldo I was improving here several functions
can you test now and tell me what do you think?
https://autocosts.work/

**Comment by jfoclpf** [comment]
is it solved?

João Pimentel Ferreira <http://joaopimentel.eu>

**Comment by mcristaldo** [comment]
Perfect, it's solved.
