### ISSUE TITLE
Home page loading issue

### ISSUE THREAD

**Issue by mcristaldo** [jfoclpf/autocosts#46]
When the page is loading I can see both sidebars opened before the home loads, it doesn't looks good.
Screenshot: https://www.dropbox.com/s/6vdq08b5v4io4zd/loading_issue.gif?dl=0

**Comment by jfoclpf** [comment]
solved with c013ca39d0e4f15f0a8b2a70d0e8d322c4f16219

**Comment by mcristaldo** [comment]
There is a text below the button that appears for a second when the page is loading "Your car cost per year"
![home-loading-issue](https://user-images.githubusercontent.com/11855774/43334412-c5f0a426-91a3-11e8-8576-43df998215cf.gif)

**Comment by jfoclpf** [comment]
solved with 020e961e796a7d638098d4ee55976e95958b33dc
