### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by mcristaldo** [jfoclpf/autocosts#49]
I know it might be too much effort but just asking. Is it possible to have more accurate error messages?
On this one for example:
![captura de pantalla 2018-07-25 18 03 10](https://user-images.githubusercontent.com/11855774/43227192-5ef9a7d8-9034-11e8-9200-c82b8cf6bd2b.png)
On this one it wouldn't makes sense if the user enter 0. So I'm wondering if the message could be something like: "Please enter the most accurate value as possible for better results"

Thoughts?

**Comment by jfoclpf** [comment]
Hi Martin, thanks for the suggestion, all effort is welcoming as long it is to improve the calculator. 

All the inputs except the date, the first two ones (month and year), 
have a `min=0` and and no `max`.

Do you mean having that message in red, under the field, on every input?

**Comment by mcristaldo** [comment]
No no, the message in red should be visible only if there is an error while completing the form OR if they didn't complete a field somehow. I think it's fine now, we can close this issue
