### ISSUE TITLE
Error on steps

### ISSUE THREAD

**Issue by mcristaldo** [jfoclpf/autocosts#51]
Make the step name red too
![captura de pantalla 2018-07-25 18 17 17](https://user-images.githubusercontent.com/11855774/43227837-4c796326-9036-11e8-822f-792e94c242c7.png)

**Comment by jfoclpf** [comment]
solved with d0f15d5e38fadec2251c5b999116a87c325636fb

**Comment by mcristaldo** [comment]
Perfect
