### ISSUE TITLE
Vertical center the question that the user is on

### ISSUE THREAD

**Issue by mcristaldo** [jfoclpf/autocosts#52]
Once a  question is completed and I click Next, the next question should be vertical centered. Now the question on focus appears too far at the bottom
![captura de pantalla 2018-07-25 18 22 43](https://user-images.githubusercontent.com/11855774/43228091-0250934a-9037-11e8-846c-a62a68941ff2.png)

**Comment by jfoclpf** [comment]
solved with e9123c2dfbd06e09b2f91093d174b1039847d04a

**Comment by mcristaldo** [comment]
Looks great Joao!
