### ISSUE TITLE
Margin on Step 2, question 1

### ISSUE THREAD

**Issue by mcristaldo** [jfoclpf/autocosts#53]
Remove left margin on this question: 
![captura de pantalla 2018-07-25 18 24 31](https://user-images.githubusercontent.com/11855774/43228182-3dfc3ce6-9037-11e8-8b61-7897e44ea34c.png)

**Comment by jfoclpf** [comment]
solved with e46b2f26b64a272528de2889326bb538750bc1a0

updated to autocosts.work

**Comment by mcristaldo** [comment]
I assigned this one to myself ha. But awesome, it looks great. Thanks
