### ISSUE TITLE
Sidebar open and close issues

### ISSUE THREAD

**Issue by mcristaldo** [jfoclpf/autocosts#56]
1. When the opening the sidebars it has a weird effect, like if everything came up from the side that doesn't looks good. I wasn't able to fix it. Are you able to fix it?
2. The only way to close it is by clicking on X icon. It would be nice if the user could close it by clicking outside the sidebar
![sidebar-opening-effect](https://user-images.githubusercontent.com/11855774/43228817-0bec4212-9039-11e8-82c7-93a0a8ab46f8.gif)

**It would be great if it works exactly like this one** (we don't need to change the X position though):
![invision_sidebar](https://user-images.githubusercontent.com/11855774/43228813-07e57c7e-9039-11e8-8e47-296b80fc90bd.gif)

**Comment by jfoclpf** [comment]
Martin, I think I solved these issues 1) and 2) with  9d2133a4f0c3e89ef78874b7007ece69e6d4cb14

can you kindly confirm? https://autocosts.work/US

please, you are responsible to close the issues when you think is UX/UI ok :)
