### ISSUE TITLE
Step 2 and 3 titles animation

### ISSUE THREAD

**Issue by mcristaldo** [jfoclpf/autocosts#57]
When the title of the step 2 and 3 come up, it has a weird animation, like entering by it self from bottom to top. It should appears together with the next question, just scrolling and fading from the bottom, like the other questions do. 
_It might be hard to see it in the GIFs I attached, in that case please check out the site online._
![effect-big-title-step](https://user-images.githubusercontent.com/11855774/43605831-0be45fc4-9670-11e8-86c6-e1eda8f08b08.gif)

![effect-big-title-step-3](https://user-images.githubusercontent.com/11855774/43605835-0e498a5a-9670-11e8-83e3-159142643c46.gif)

**Comment by jfoclpf** [comment]
solved with f433751bcb11e6b288a16ba05e83fe04b6f68b0a

**Comment by jfoclpf** [comment]
can you test now?
