### ISSUE TITLE
Car riding on the main page

### ISSUE THREAD

**Issue by jfoclpf** [jfoclpf/autocosts#60]
Hi @mcristaldo 

1) When we zoom out, the road is not aligned horizontally, which is a bit strange

2) The car doesn't drive fully from the left to the far right

![image](https://user-images.githubusercontent.com/3984909/44036990-85a0cf68-9f13-11e8-8640-d2d4437c0509.png)

Do you think you can solve these two issues?

**Comment by mcristaldo** [comment]
Issue solved.
Please check it out here https://autocosts.work/

Thanks

**Comment by jfoclpf** [comment]
It works nice now
It's nice two cars, it gives a notion of traffic.
The road is flat and smooth!
Thanks

**Comment by mcristaldo** [comment]
Yeah, that's true it gives a notion of traffic, which is cool. I didn't realize about it before.
Thanks
