### ISSUE TITLE
File img/dd_arrow-white.png is missing

### ISSUE THREAD

**Issue by jfoclpf** [jfoclpf/autocosts#62]
On css file `results.css` there is this line

`#info-boxes .container .info-box select {background: url('../img/dd_arrow-white.png'); color: white; border-color: white; font-size: 22px; text-transform: lowercase;}`

Though file `../img/dd_arrow-white.png` is missing

Please @mcristaldo add file `dd_arrow-white.png` to `src/img` directory

Thank you

**Comment by jfoclpf** [comment]
@mcristaldo , file `results.css` has this line

`#info-boxes .container .info-box select {background: url('../img/dd_arrow-white.png'); color: white; border-color: white; font-size: 22px; text-transform: lowercase;}`

But file `img/dd_arrow-white.png ` is not there

![screenshot from 2018-09-15 22-26-49](https://user-images.githubusercontent.com/3984909/45590348-b45a7600-b936-11e8-8fb2-058acfa3ccc7.png)

**Comment by mcristaldo** [comment]
Issue fixed. Closing issue
