### ISSUE TITLE
Reading issues on costs sidebar

### ISSUE THREAD

**Issue by mcristaldo** [jfoclpf/autocosts#65]
Screenshot: https://www.dropbox.com/s/ute59soft7ncxm3/Captura%20de%20pantalla%202018-09-20%2009.25.40.png?dl=0

Since everything is tight to fit all the information in the screen, it's hard to scan the information, so I might add some lines to connect the text with the number to make the thing a bit more clear when reading

**Comment by jfoclpf** [comment]
cool! The applicable file is this one: https://github.com/jfoclpf/autocosts/blob/newUI/src/views/partials/sidebars.hbs

I suppose you need the class `sidebar-right-container`

Any issues let me know

**Comment by mcristaldo** [comment]
Solved, please check it out

![captura de pantalla 2018-09-26 13 17 24](https://user-images.githubusercontent.com/11855774/46093679-59265000-c18e-11e8-9cdf-19b409016fd7.png)

**Comment by jfoclpf** [comment]
Perfect! Thanks a lot, it's very nice!
