### ISSUE TITLE
too many arrows

### ISSUE THREAD

**Issue by jfoclpf** [jfoclpf/autocosts#67]
![screenshot from 2018-09-20 20-19-04](https://user-images.githubusercontent.com/3984909/45838646-88623a80-bd12-11e8-8393-c49a2216ec5f.png)

@mcristaldo , I added the arrow jpg / png file file but too many arrows appear

**Comment by jfoclpf** [comment]
Hi Martin

As any professional website/node project, we have two main root folders `/src` and `/bin`.
When the project is built, the files from `/src` are processed to produce the `/bin`. Basically the build process minifies and merges some files, to be available online.

* In github you only see the files in `/src`, and 
* in `/bin` you would see the online/.work 

When the site is built from `/src` to `/bin`, [it merges the css files into only two files](https://github.com/jfoclpf/autocosts/blob/c0235cb7e6bb0ab25030a2f9a1fbe369cd5458ac/build.js#L208) .

Besides that, I just reorganised the folders where the css files are stored, I didn't change any file substantially.

> Are these ready?

Yes, they are ready.

> Did you updated these changes on the .work URL too?

Yes, I updated, but again, what you see on .work is different from github.

The files `'style.css', 'responsive.css', 'fonts.css'` from `/src` are merged into `'merged_init.css'` on `/bin`

And the file ` 'results.css'` from `/src` will be `'merged_deferred.css'`

Sorry the mess, but we need this for fast initial loading of the website.

**Comment by jfoclpf** [comment]
Hi Martin

Never mind :) 

To ease your tests, I reverted the built issues, and you can edit the css files directly in .work and see the results directly online. Check the commit 26b6cccf549101b0b1c7258f9221be4013fb3632 and you'll understand. Any issues let me know

Cheers and thank you

**Comment by mcristaldo** [comment]
Fixed
Screenshot: https://www.dropbox.com/s/qffqxqju1d68s8c/Captura%20de%20pantalla%202018-09-21%2017.37.17.png?dl=0
