### ISSUE TITLE
insert new text in language files

### ISSUE THREAD

**Issue by jfoclpf** [jfoclpf/autocosts#72]
Insert new properties of global variable `WORDS` for different languages.

When such property is not available for the current language, use the English version

**Comment by jfoclpf** [comment]
Advanced work. Commits from ade92d85f0572a471641c0d2923b352365924d98 to d6a21ea014c86b6078cdfd55ed2d38bb869ab615

All changes here: https://github.com/jfoclpf/autocosts/compare/ade92d8..d6a21ea

**Comment by jfoclpf** [comment]
These were the new strings needed for the new design

```
"sub_title" : "The average total costs in [country] is [yearly_costs] per year, representing [nbrMonths] months of average salary. Find the true cost of owning a car in your country.",
"press_enter_or_tab": "press <b>Enter</b> or <b>Tab</b>",
"calculate_car_costs": "Calculate car costs",
"in_months_of_possession": "in [nbrMonths] months of possession",
"of_your_income": "of your income",
"next": "Next",
"edit_form": "Edit form",
"share" : "Share",
"close": "Close",
```

@mcristaldo could you kindly make the Spanish translation?

**Comment by jfoclpf** [comment]
@mcristaldo I have already spanish, what do you think?
https://autocosts.work/NI

I will still need to arrange for Italian, French, Romanian, Swedish, Norwegian and Polish .
I may use Google Translate

**Comment by mcristaldo** [comment]
Hi @jfoclpf 
Looks great, I reviewed all the pages and I didn't see any error.

**Comment by jfoclpf** [comment]
These strings need to be translated 

```
"sub_title" : "The average total costs in [country] is [yearly_costs] per year, representing [nbrMonths] months of average salary. Find the true cost of owning a car in your country.",
"press_enter_or_tab": "press <b>Enter</b> or <b>Tab</b>",
"calculate_car_costs": "Calculate car costs",
"in_months_of_possession": "in [nbrMonths] months of possession",
"of_your_income": "of your income",
"next": "Next",
"edit_form": "Edit form",
"share" : "Share",
"close": "Close",
```

to **French, Italian, German, Hungarian, Greek, Polish, Czech, Romanian, Dutch, Swedish, Norwegian, Danish, Finish, Russian, Ukrainian, Turkish, Indian, Japanese and Chinese**

**Comment by jfoclpf** [comment]
added remaining strings with 46b9878e80ec7eec0b2916df750c9cbe19549454

missing only JP and CN
