### ISSUE TITLE
New chart on results

### ISSUE THREAD

**Issue by jfoclpf** [jfoclpf/autocosts#73]
Hi @mcristaldo 

I know it should have been though during the design phase, but we miss a relevant chart on the first section (monthly costs), which is like a pie chart, showing the percentage of each cost item in terms of overall costs, like we had on the previous version.

This gives the user a very good idea, of what are the major costs in terms **of percentage**. 

This is what we had, though not so pretty

![image](https://user-images.githubusercontent.com/3984909/47240306-36cbcf00-d3e8-11e8-8269-e93364bfb641.png)

Can you think of something cool, using the [chartJs library](http://www.chartjs.org/samples/latest/), to be integrated in our results, without removing the previous ones?

What do you think? Does it get too imagetic? Too crowded with charts?

**Comment by mcristaldo** [comment]
Hi @jfoclpf 
Oh sure, we can add this. Let me re-look at the results designs page to see where and how we can fit this pie chart and I'll back to you.

Thanks

**Comment by jfoclpf** [comment]
Thanks Martin
It doesn't need to be a pie, it may be a doughnut
http://www.chartjs.org/samples/latest/charts/doughnut.html

João Pimentel Ferreira <http://joaopimentel.eu>

**Comment by jfoclpf** [comment]
Perfect @mcristaldo 

Can you change the `results.css` and the `results.hbs` accordingly, such that I can insert the graph therein?

Thank you

**Comment by jfoclpf** [comment]
I like it very much @mcristaldo 
I like the proportion in widths, but considering the vertical axis on the bar chart, wouldn't be better to swap their positions, and put the bar chart on the left side? What do you think?

**Comment by mcristaldo** [comment]
Hi @jfoclpf,
Good idea, it looks more balanced with the doughnut on the left instead.
Please check it out: https://www.dropbox.com/s/li538oaredxio3o/ac_results-v2-op2.jpg?dl=0

**Comment by jfoclpf** [comment]
Looks great @mcristaldo , thank you. You may advance. Can you change the `results.css` and the `results.hbs` accordingly, such that I can insert the graph therein?

**Comment by mcristaldo** [comment]
Sure thing, I'll update the files and commit it once it's done

**Comment by mcristaldo** [comment]
I commited the files with the doughnut chart included. Please check it out when you get the chance.
Thank you.

**Comment by jfoclpf** [comment]
Hi @mcristaldo 
I added the doughnut chart. I restored to your original suggestion on the left.
Check https://autocosts.work/XX. What do you think?
I made some css changes on `results.css` here 47dc08e49597de4e49fc25d53bfcc9bb87d4eecd and on `responsive.css` here 0134769b06b43d7260139bbd385155ba0b7c7622
Can you kindly do some final css refinements, if necessary? 

When you think it's ok, responsive included, you may close the issue.

**Comment by jfoclpf** [comment]
## Solved

### js 

216fe345943bd91ce5f3bb4066d36aea6d8d195b and 5946b73881872784a0d5484b63d104744e30370d, 

### html/css

469efed40d26abbc18869a2fa711d81c1b3f258b and 47dc08e49597de4e49fc25d53bfcc9bb87d4eecd

### css

b319da321ea4b4f5b046e77ea0ec1d4a4d251c45, 0134769b06b43d7260139bbd385155ba0b7c7622 and efc59171403de2a01708e1f8cac0145cbca84086

## Todo

@mcristaldo 

I'm closing the issue, but if you feel that some css issues still remain to be improved with either one the bars or doughnut charts, their interaction or their responsive behaviour, feel free to edit the files and commit. 

If you do it, comment here with the corresponding commits, since comments are allowed after closing an issue.

### How to make links to commits

To have here a link to a commit, just copy-paste the commit hunk at the top right of the commit page, for example [this one](https://github.com/jfoclpf/autocosts/commit/469efed40d26abbc18869a2fa711d81c1b3f258b):

![image](https://user-images.githubusercontent.com/3984909/47605298-f7fbd180-da04-11e8-8b1f-07986016da47.png)

**Comment by jfoclpf** [comment]
If you think the design of the two top charts is already ok, you may leave it
