### ISSUE TITLE
CSS for /stats page

### ISSUE THREAD

**Issue by jfoclpf** [jfoclpf/autocosts#74]
Hi @mcristaldo 

Adopting the same design style of the calculator, could you kindly write the CSS rules for the overall statistical page?

http://autocosts.work/stats

The html/hbs page is at [`src/views/stats.hbs`](https://github.com/jfoclpf/autocosts/blob/newUI/src/views/stats.hbs) and the CSS file is at [`css/worldStats/main.css`](https://github.com/jfoclpf/autocosts/blob/newUI/src/css/worldStats/main.css)

Delete all the previous CSS rules if you need to.
Any questions let me know

Thank you so much

**Comment by mcristaldo** [comment]
Hi Joao, 

Where this page come from? I just want to understand how the users are able to reach this page.

Thank you.

**Comment by jfoclpf** [comment]
Hi Martin. It should work

https://autocosts.work/stats

**Comment by mcristaldo** [comment]
Hi Joao, 

Yes sure, I saw the link already, the design is almost finish actually. What I meant is how the users reach to this page? is there a link on the sidebars or something, or they need the link to get access to this page?

Thank you.

**Comment by jfoclpf** [comment]
Good point Martin
Actually I developed that page separately and I didn't think of it.
What do you suggest? I was wondering about a link somewhere around the
right bar where the chart appears.
Ideas are welcomed :)

**Comment by mcristaldo** [comment]
Hi Joao, 

Finally I have the design for the World Stats page.
Please take a look: https://www.dropbox.com/s/t5ajcth8n532kk9/ac_stats.jpg?dl=0

Also I've placed a link in the right sidebar to access to this page. I put it on the right of the country dropdown at the top. Please let me know your thoughts.
https://www.dropbox.com/s/rjcxhzezaebcw6g/Captura%20de%20pantalla%202018-11-09%2018.00.12.png?dl=0

Once you approve this design I'll start coding the page.

Thank you

**Comment by jfoclpf** [comment]
Hi Martin
It's very good, thank you.
I just see an issue with mobile version.
That chart will be too shrunk and compact in mobile version, that's why I
put it on horizontal bars.
What do you think? Ideas?

**Comment by mcristaldo** [comment]
Hi Joao, 
Sorry for the delay. 

I have a couple of comments about the charts

1. It's hard to distinguish the low values on the bars, from a visual perspective. Even though there is a tooltip for each bar.
**Possible solution**: setup Standing costs and Running costs as 2 different charts. It could be applied for results page too. Thoughts?

2. About mobile, from a technical perspective (also thinking about time consuming), is it possible to show the charts differently for desktop and mobile? so we can use vertical bars on desktop and horizontal bars on mobile

Thank you

**Comment by jfoclpf** [comment]
Hi Martin
Thank you for the reply

1. Splitting is not a good idea because the total overall costs of the car get dispersed and it's not possible anymore to compare the total costs amongst countries.

2. Nice point, yes it should be. We can try to at least detect the window's width and change the charts orientation accordingly. Nice point!

You can start updating the css for the charts. It's this file: https://github.com/jfoclpf/autocosts/tree/master/src/css/worldStats

**Comment by jfoclpf** [comment]
@mcristaldo I realised that you made a great job in the stats page https://autocosts.work/stats
Thanks. Can you send me the files that I upload them to the system and github?

**Comment by mcristaldo** [comment]
Hey @jfoclpf 
I downloaded the github desktop app, so it's easier for me to keep track on things and download and commit files. I commited everything on Sunday, didn't you get a notification about it?

**Comment by mcristaldo** [comment]
I'm still working on the responsive version for this Stats page though

**Comment by jfoclpf** [comment]
Ah ok, cool. I need to update the repository on my local side. I will check
it

**Comment by mcristaldo** [comment]
Hi @jfoclpf 
I'm working on the responsive view for Stats. Not sure what the reason is, but style.css is not working anymore. For some reason the site is not linking this file, even though it's on the server. 
Do you min checking it when you get the chance please?

Thank you

**Comment by jfoclpf** [comment]
Hi @mcristaldo 
Solved!
It had to do with the file permissions.
Check the file permissions on filezilla
Regards

**Comment by mcristaldo** [comment]
Awesome, thank you very much.

**Comment by jfoclpf** [comment]
Hi @mcristaldo 

I merged your updates with my changes and changes are already here on github and online
https://autocosts.work/stats

if you have already a local git software, _update the code to your local machine_

I realised that we cannot actually really make vertical bars on the chart, since we can have several countries, and the number of countries is growing and will grow further, and all those bars do not fit side-by-side. Therefore we must keep the horizontal bars.

Any more changes that you'd like to make or suggest before closing this issue?
Maybe the thickness or the height of the bars?

Check: https://autocosts.work/stats

cheers and thank you

**Comment by mcristaldo** [comment]
Hi @jfoclpf 

Great, thanks for letting me know. 
I'm struggling with the tables on mobile, it looks good on Chrome testing in my pc, but it's not looking good on my iPhone, I have been trying different alternatives but for some reason it doesn't display properly. I'll do my best to solve this today, after solving that this issue would be ready to be closed.
I'll let you know.

The vertical bars looks fine. The only thing I noticed is that the references are duplicated, cause I added these manually on HTML. Are we able to customize the references style that were generated from the charts you installed? It would be nice to keep yours references cause the user is able to filter using those references.
Screenshot: https://www.dropbox.com/s/50q4igfe2hf53eq/Captura%20de%20pantalla%202018-12-17%2012.58.41.png?dl=0

**Comment by mcristaldo** [comment]
Got it, no problem. I'll try to solve it within an hour. Sounds good?

**Comment by mcristaldo** [comment]
Hi Joao, 

The stats page is done, I checked it out on desktop and mobile and it looks good. Would you check it out when you get the chance please?

Btw, the home page is only displaying the header and footer animation but not the text and button on iPhone, would you check that too please?

Thank you.

**Comment by jfoclpf** [comment]
Hi Martin

>The only thing I noticed is that the references are duplicated, cause I added these manually on HTML. Are we able to customize the references style that were generated from the charts you installed? It would be nice to keep yours references cause the user is able to filter using those references.

Can you check now?
https://autocosts.work/stats
What do you think? 
Code updates are already in github

> the home page is only displaying the header and footer animation but not the text and button on iPhone, would you check that too please?

I made some changes on that, to avoid the text to appear on a clumsy way. Can you try to make a hard refresh on your iPhone browser and confirm that?

Thanks

**Comment by jfoclpf** [comment]
anyway something's wrong on the table CSS which I cannot detect, can you check?

**Comment by mcristaldo** [comment]
Hi Joao, 

The references look good. Thank you.
The stats.hbs file got overwritten. I uploaded it to Github but now I'm not able to upload to autocosts.work. I'm getting the same error as always "553 Could not create file."

**Comment by jfoclpf** [comment]
Can you check now the stats.hbs?

I overwrote with the code that was on github. It means that it was not
correctly updated on github. Could you kindly update in github if necessary?

Thank

**Comment by mcristaldo** [comment]
Hi Joao, 
I already updated on github but I'm still not able to upload to the website. I'm getting the same error.

Thank you.

**Comment by jfoclpf** [comment]
Thanks, I found the issue, the server hadn't the correct files from github.
Now it's solved

**Comment by mcristaldo** [comment]
Hi Joao, 

I just realized that the files uploaded for this page are not the correct ones. 

I'm not able to upload this via FTP to re-test the site but the files in Github aren't the last version I created. I'm getting the same 553 error as always.

I'm not using table tag anymore, I used divs to create the tables cause it works better on mobile as well as it allows more control.

Github is having some kind of conflict when I'm trying upload these files. Would you check it out please and update accordingly if it works fine.
Please check out the files:
Stats.hbs: https://www.dropbox.com/s/am2rvv6ntw0c2it/stats.hbs?dl=0
Main.css: https://www.dropbox.com/s/tcjqbq77a9twoti/main.css?dl=0

Thank you.

**Comment by jfoclpf** [comment]
are these the files you want to upload?

Stats.hbs: https://www.dropbox.com/s/hg4zb4na95xw6tq/stats_backup2.hbs?dl=0
Main.css: https://www.dropbox.com/s/tcjqbq77a9twoti/main.css?dl=0

the conflict is due to the fact that maybe I edited those files

**Comment by jfoclpf** [comment]
I upload them, don't worry

**Comment by jfoclpf** [comment]
css file is giving error

@mcristaldo , forget it, we need to advance and we're losing too much time on details

**Comment by jfoclpf** [comment]
thanks
João Pimentel Ferreira <http://joaopimentel.eu>
