### ISSUE TITLE
replace pinterest share button by whatsApp

### ISSUE THREAD

**Issue by jfoclpf** [jfoclpf/autocosts#75]
WhatsApp is a more relevant share media than pinterest.

Please replace button and classes accordingly

![image](https://user-images.githubusercontent.com/3984909/47243092-4a2f6800-d3f1-11e8-8c96-58f7c9895008.png)

Thank you

**Comment by mcristaldo** [comment]
Hi Joao, 

I've trying to replace the icon, but after uploading bottom_action_bar.hbs file it through FileZilla it seems the site doesn't get updated for some reason, I tried several times but noting happen. Would you please check why is this happening.
Here is the file: https://www.dropbox.com/s/xojxefq67eg4yf0/bottom_actions_bar.hbs?dl=0

**Comment by mcristaldo** [comment]
It's not only happening with the bottom bar, I also tried to update the results.hbs file and the changes are not reflecting in the URL for some reason

**Comment by jfoclpf** [comment]
@mcristaldo can you try now and give some feedback
Thanks

**Comment by mcristaldo** [comment]
Hi @jfoclpf 
Sorry for the delay.
It's still not working, I tried uploading the files again but nothing happen.
I did a GIF so you can see what I'm doing https://www.dropbox.com/s/32qjg2v4yv6nfzf/autocosts-issue-uploading-files-ftp.gif?dl=0

**Comment by jfoclpf** [comment]
@mcristaldo 
it is indeed changing like a charm :)
do kindly check:

![image](https://user-images.githubusercontent.com/3984909/47746133-c80f3100-dc85-11e8-9621-cc65a2f4dcae.png)

![image](https://user-images.githubusercontent.com/3984909/47746309-2e944f00-dc86-11e8-8f5d-3c30b342bbe1.png)

You just changed the content of mobile div, that is, `.right-actions-mobile`. 

Thank you so much

**Comment by mcristaldo** [comment]
Oh man! Even though I built it myself I forgot I have one div for mobile only. Sorry for wasting your time.
Btw, I don't see a initialize.css file (I checked out several times ha)

PS.: Of course **I won't charge for it**, no worries and sorry again

**Comment by jfoclpf** [comment]
No problems at all. Now my fault :) 
There is no `initialize.css`.

**Comment by mcristaldo** [comment]
Hi Joao, I just changed the Pinterest icon to Whatsapp, would you check it out and close if everything is fine?
Thank you.

**Comment by jfoclpf** [comment]
Thanks
