### ISSUE TITLE
Uniformize colors variables

### ISSUE THREAD

**Issue by jfoclpf** [jfoclpf/autocosts#77]
The costs colors come from different places and variables.
Uniformize origin of said colors, such that all that info comes from the same place, preferably `commons.js`

**Comment by jfoclpf** [comment]
or maybe create a seperate css file `colors.css`

**Comment by jfoclpf** [comment]
@mcristaldo can you create a separate file `colors.css`, only for the colors of each cost item?

[Just this information](https://github.com/jfoclpf/autocosts/blob/newUI/src/css/results.css#L52).

**Comment by mcristaldo** [comment]
Oh I saw that you already created colors.css

**Comment by jfoclpf** [comment]
yes, apologies for the anticipation. Solved with this commit: 37feec86d1655a0c8da30a5e676fd83a71437d43
