### ISSUE TITLE
Change terminology in CSS classes

### ISSUE THREAD

**Issue by jfoclpf** [jfoclpf/autocosts#78]
Hi @mcristaldo 

I changed the name of color classes, due to harmonisation of terms, throughout the project.

The cost items' terminology should be, for programmatic purposes:

```
car_tax,
credit,
depreciation,
fines,
fuel,
inspection,
insurance,
maintenance,
parking,
repairs_improv,
tolls,
washing
```

You can check these differences in the corresponding commit: b6a15e8c3bba42193f31eff69d9279664eaaa417

**Comment by jfoclpf** [comment]
When you have read this message, you may close the issue

**Comment by mcristaldo** [comment]
Perfect! Closing issue
