### ISSUE TITLE
The branch master is now our working branch

### ISSUE THREAD

**Issue by jfoclpf** [jfoclpf/autocosts#83]
@mcristaldo 

#### 1) Commit on master

I moved our working branch to the branch `master`. Since we are leading the work and the development of the project, there is no sense to develop in a different branch. 

From now on, you commit on the main branch, the branch `master`.
https://github.com/jfoclpf/autocosts

![image](https://user-images.githubusercontent.com/3984909/47532896-ed7cf300-d8b1-11e8-8b40-0a0acae5bafb.png)

![image](https://user-images.githubusercontent.com/3984909/47532922-fff72c80-d8b1-11e8-8324-5deeb38683ee.png)

#### 2) Preview changes

But please, I insist, always preview your changes before committing, such that you are aware of the changes your are about to supply, and they meet what you expect to be.

![image](https://user-images.githubusercontent.com/3984909/47532985-3d5bba00-d8b2-11e8-9507-989198a1f481.png)

You may close this issue after you have read it.

Thank you very much

**Comment by mcristaldo** [comment]
Sounds perfect. Thank you.
