### ISSUE TITLE
Having no net income the final result is infinite

### ISSUE THREAD

**Issue by NCCLPF** [jfoclpf/autocosts#92]
![image](https://user-images.githubusercontent.com/44784435/49013949-bd5d9400-f17e-11e8-90c7-79732dabf33b.png)
Having no net income in the field "3. Public transports & Financial effort - What is your net income? - Year or Month or Week or Hour" the final result shows infinite:
![image](https://user-images.githubusercontent.com/44784435/49014234-c26f1300-f17f-11e8-8939-743e2dc05b02.png)

**Comment by jfoclpf** [comment]
thanks @NCCLPF 
issue solved with 5817ebc
Can you try now, when you have time, just to be sure that this issue is solved? :) 
https://autocosts.work/XX
