### ISSUE TITLE
Any error if I drive to work a couple of days and do at the same time 0 Miles in that way

### ISSUE THREAD

**Issue by NCCLPF** [jfoclpf/autocosts#93]
![image](https://user-images.githubusercontent.com/44784435/49015168-90ab7b80-f182-11e8-9a02-5febd81d540c.png)
It doesn't show any error in the field "3. Public transports & Financial effort - Distance - Considering you drive to work? - Yes", if I drive to work for example 3 days and do 0 Mi driving between home and workplace. It doesn't show also any error in the final results.

**Comment by jfoclpf** [comment]
issue solved with 5817ebc1f1958ee33e6b96191e041fd1349f1d50
Thanks @NCCLPF
