### ISSUE TITLE
No relation between the Miles that I do to work/weekends and how many minutes I spend to do that

### ISSUE THREAD

**Issue by NCCLPF** [jfoclpf/autocosts#94]
In the field "3. Public transports & Financial effort - Distance - Considering you drive to work? - Yes - Miles you drive between home and workplace (just one way)" I can put 20 Mi and at the same time in the field "3. Public transports & Financial effort - How many minutes you drive from home to workplace? (just one way)", I can put 0 min that it doesn't appear any error and it shows the final results without any problem.
![image](https://user-images.githubusercontent.com/44784435/49016282-e2a1d080-f185-11e8-8067-0bff688e6aef.png)
![image](https://user-images.githubusercontent.com/44784435/49016304-fbaa8180-f185-11e8-83cb-6bd810d0e0b3.png)
The same happens when I do Miles during the days I don't take the car to workplace (for example weekends) and the respective minutes that I spend to do that: 
![image](https://user-images.githubusercontent.com/44784435/49016555-c18daf80-f186-11e8-970a-01e8d7477c69.png)
![image](https://user-images.githubusercontent.com/44784435/49016588-d702d980-f186-11e8-8549-5cf093c9f5bc.png)
Neither the other way around... no relation between these two fields.

**Comment by jfoclpf** [comment]
Thank you very much for finding that bug @NCCLPF

I think it can be solved with restrictions on the field input. Some inputs should only accept numbers greater than zero, and not equal zero.

Functions in ValidateFormModule should thus be amended accordingly.

**Comment by jfoclpf** [comment]
partially solved with 7f09cf57f15d04d80f10925274edf60923570f9e
thanks for the tip @NCCLPF
